################################################################################
# This file was auto-generated by generate_state_variable_form.py
################################################################################
import numpy as np


def calculate_eom(x, u, m, ell, b):
    [theta, thetadot] = x.flatten()  # ensure 1D
    [tau] = u.flatten()  # ensure 1D
    eom = np.array([[thetadot], [-3.0*b*thetadot/(ell**2*m) - 14.7*np.cos(theta)/ell + 3.0*tau/(ell**2*m)]])
    return eom.squeeze()
