################################################################################
# This file was auto-generated by generate_state_variable_form.py
################################################################################
import numpy as np


def calculate_M(x, m1, m2, m3, J1_x, J1_y, J1_z, J2_x, J2_y, J2_z, J3_x, J3_y, J3_z, ell1, ell2, ell3_x, ell3_y, ell3_z, ell_T, d, g):
    [phi, theta, psi, phidot, thetadot, psidot] = x.flatten()  # ensure 1D
    M = np.array([[J1_x, 0, -J1_x*np.sin(theta)], [0, -J1_y*np.sin(phi)**2 + J1_y + J1_z*np.sin(phi)**2 + J2_y + ell1**2*m1 + ell2**2*m2, (J1_y - J1_z)*np.sin(phi)*np.cos(phi)*np.cos(theta)], [-J1_x*np.sin(theta), (J1_y - J1_z)*np.sin(phi)*np.cos(phi)*np.cos(theta), -J1_x*np.cos(theta)**2 + J1_x - J1_y*np.cos(phi)**2*np.cos(theta)**2 + J1_y*np.cos(theta)**2 + J1_z*np.cos(phi)**2*np.cos(theta)**2 - J2_x*np.cos(theta)**2 + J2_x + J2_z*np.cos(theta)**2 + J3_z + ell1**2*m1*np.cos(theta)**2 + ell2**2*m2*np.cos(theta)**2 + ell3_x**2*m3 + ell3_y**2*m3]])
    return M.squeeze()


def calculate_C(x, m1, m2, m3, J1_x, J1_y, J1_z, J2_x, J2_y, J2_z, J3_x, J3_y, J3_z, ell1, ell2, ell3_x, ell3_y, ell3_z, ell_T, d, g):
    [phi, theta, psi, phidot, thetadot, psidot] = x.flatten()  # ensure 1D
    C = np.array([[-J1_x*psidot*thetadot*np.cos(theta) - 1/2*psidot*(2*psidot*(J1_y - J1_z)*np.sin(phi)*np.cos(phi)*np.cos(theta)**2 + thetadot*(J1_y - J1_z)*np.cos(2*phi)*np.cos(theta)) - 1/2*thetadot*(psidot*(J1_y - J1_z)*np.cos(2*phi)*np.cos(theta) + thetadot*(-J1_y + J1_z)*np.sin(2*phi))], [(1/2)*J1_x*phidot*psidot*np.cos(theta) + phidot*thetadot*(-2*J1_y*np.sin(phi)*np.cos(phi) + 2*J1_z*np.sin(phi)*np.cos(phi)) + (1/2)*psidot*thetadot*(J1_y - J1_z)*np.sin(phi)*np.sin(theta)*np.cos(phi) + psidot*(J1_y - J1_z)*(-2*phidot*np.sin(phi)**2*np.cos(theta) + phidot*np.cos(theta) - thetadot*np.sin(phi)*np.sin(theta)*np.cos(phi)) - 1/2*psidot*(-J1_x*phidot*np.cos(theta) + 2*psidot*(J1_x - J1_y*np.sin(phi)**2 - J1_z*np.cos(phi)**2 + J2_x - J2_z - ell1**2*m1 - ell2**2*m2)*np.sin(theta)*np.cos(theta) - thetadot*(J1_y - J1_z)*np.sin(phi)*np.sin(theta)*np.cos(phi))], [-J1_x*phidot*thetadot*np.cos(theta) - 2*psidot*(phidot*(-J1_y + J1_z)*np.sin(phi)*np.cos(phi)*np.cos(theta) + thetadot*(-J1_x + J1_y*np.sin(phi)**2 + J1_z*np.cos(phi)**2 - J2_x + J2_z + ell1**2*m1 + ell2**2*m2)*np.sin(theta))*np.cos(theta) + thetadot*(J1_y - J1_z)*(-2*phidot*np.sin(phi)**2*np.cos(theta) + phidot*np.cos(theta) - thetadot*np.sin(phi)*np.sin(theta)*np.cos(phi))]])
    return C.squeeze()


def calculate_dP_dq(x, m1, m2, m3, J1_x, J1_y, J1_z, J2_x, J2_y, J2_z, J3_x, J3_y, J3_z, ell1, ell2, ell3_x, ell3_y, ell3_z, ell_T, d, g):
    [phi, theta, psi, phidot, thetadot, psidot] = x.flatten()  # ensure 1D
    dP_dq = np.array([[0], [ell1*g*m1*np.cos(theta) + ell2*g*m2*np.cos(theta)], [0]])
    return dP_dq.squeeze()


def calculate_tau(x, u, m1, m2, m3, J1_x, J1_y, J1_z, J2_x, J2_y, J2_z, J3_x, J3_y, J3_z, ell1, ell2, ell3_x, ell3_y, ell3_z, ell_T, d, g):
    [phi, theta, psi, phidot, thetadot, psidot] = x.flatten()  # ensure 1D
    [f_l, f_r] = u.flatten()  # ensure 1D
    tau = np.array([[d*(f_l - f_r)], [ell_T*(f_l + f_r)*np.cos(phi)], [-d*(f_l - f_r)*np.sin(theta) + ell_T*(f_l + f_r)*np.sin(phi)*np.cos(theta)]])
    return tau.squeeze()
