################################################################################
# This file was auto-generated by generate_state_variable_form.py
################################################################################
import numpy as np


def calculate_eom(x, u, m1, m2, ell, b):
    [z, theta, zdot, thetadot] = x.flatten()  # ensure 1D
    [F] = u.flatten()  # ensure 1D
    eom = np.array([[zdot], [thetadot], [-4.0*F/(3.0*m1*np.cos(theta)**2 - 4.0*m1 - 4.0*m2) + 4.0*b*zdot/(3.0*m1*np.cos(theta)**2 - 4.0*m1 - 4.0*m2) - 2.0*ell*m1*thetadot**2*np.sin(theta)/(3.0*m1*np.cos(theta)**2 - 4.0*m1 - 4.0*m2) + 29.4*m1*np.sin(theta)*np.cos(theta)/(3.0*m1*np.cos(theta)**2 - 4.0*m1 - 4.0*m2)], [6.0*F*np.cos(theta)/(3.0*ell*m1*np.cos(theta)**2 - 4.0*ell*m1 - 4.0*ell*m2) - 6.0*b*zdot*np.cos(theta)/(3.0*ell*m1*np.cos(theta)**2 - 4.0*ell*m1 - 4.0*ell*m2) + 3.0*ell*m1*thetadot**2*np.sin(theta)*np.cos(theta)/(3.0*ell*m1*np.cos(theta)**2 - 4.0*ell*m1 - 4.0*ell*m2) - 58.8*m1*np.sin(theta)/(3.0*ell*m1*np.cos(theta)**2 - 4.0*ell*m1 - 4.0*ell*m2) - 58.8*m2*np.sin(theta)/(3.0*ell*m1*np.cos(theta)**2 - 4.0*ell*m1 - 4.0*ell*m2)]])
    return eom.squeeze()
